/* Copyright (c) 2008, 2009
 *      Juergen Weigert (jnweiger@immd4.informatik.uni-erlangen.de)
 *      Michael Schroeder (mlschroe@immd4.informatik.uni-erlangen.de)
 *      Micah Cowan (micah@cowan.name)
 *      Sadrul Habib Chowdhury (sadrul@users.sourceforge.net)
 * Copyright (c) 1993-2002, 2003, 2005, 2006, 2007
 *      Juergen Weigert (jnweiger@immd4.informatik.uni-erlangen.de)
 *      Michael Schroeder (mlschroe@immd4.informatik.uni-erlangen.de)
 * Copyright (c) 1987 Oliver Laumann
 *
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program (see the file COPYING); if not, see
 * http://www.gnu.org/licenses/, or contact Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA  02111-1301  USA
 *
 ****************************************************************
 */

#include "config.h"

#include "comm.h"

/* Must be in alpha order ! */

struct comm comms[RC_LAST + 1] =
{
  { U"acladd",		ARGS_1234,			{NULL} },
  { U"aclchg",		ARGS_23,			{NULL} },
  { U"acldel",		ARGS_1,				{NULL} },
  { U"aclgrp",		ARGS_12,			{NULL} },
  { U"aclumask",		ARGS_1|ARGS_ORMORE,		{NULL} },
  { U"activity",		ARGS_1,				{NULL} },
  { U"addacl",		ARGS_1234,			{NULL} },
  { U"allpartial",	NEED_DISPLAY|ARGS_1,		{NULL} },
  { U"altscreen",	ARGS_01,			{NULL} },
  { U"at",		ARGS_2|ARGS_ORMORE,		{NULL} },
  { U"autodetach",	ARGS_1,				{NULL} },
  { U"autonuke",		NEED_DISPLAY|ARGS_1,		{NULL} },
  { U"backtick",		ARGS_1|ARGS_ORMORE,		{NULL} },
  { U"bce",		NEED_FORE|ARGS_01,		{NULL} },
  { U"bell",		ARGS_01,			{NULL} },
  { U"bell_msg",		ARGS_01,			{NULL} },
  { U"bind",		ARGS_1|ARGS_ORMORE,		{NULL} },
  { U"bindkey",		ARGS_0|ARGS_ORMORE,		{NULL} },
  { U"blanker",		NEED_DISPLAY|ARGS_0,		{NULL} },
  { U"blankerprg",	ARGS_0|ARGS_ORMORE,		{NULL} },
  { U"break",		NEED_FORE|ARGS_01,		{NULL} },
  { U"breaktype",	NEED_FORE|ARGS_01,		{NULL} },
  { U"bufferfile",	ARGS_01,			{NULL} },
  { U"bumpleft",		NEED_FORE|ARGS_0,		{NULL} },
  { U"bumpright",	NEED_FORE|ARGS_0,		{NULL} },
  { U"c1",		NEED_FORE|ARGS_01,		{NULL} },
  { U"caption",		ARGS_123,			{NULL} },
  { U"chacl",		ARGS_23,			{NULL} },
  { U"charset",          NEED_FORE|ARGS_1,		{NULL} },
  { U"chdir",		ARGS_01,			{NULL} },
  { U"cjkwidth",		ARGS_01,			{NULL} },
  { U"clear",		NEED_FORE|ARGS_0,		{NULL} },
  { U"collapse",		ARGS_0,				{NULL} },
  { U"colon",		NEED_LAYER|ARGS_01,		{NULL} },
  { U"command",		NEED_DISPLAY|ARGS_02,		{NULL} },
  { U"compacthist",	ARGS_01,			{NULL} },
  { U"console",		NEED_FORE|ARGS_01,		{NULL} },
  { U"copy",		NEED_FORE|NEED_DISPLAY|ARGS_0,	{NULL} },
  { U"crlf",		ARGS_01,			{NULL} },
  { U"defautonuke",	ARGS_1,				{NULL} },
  { U"defbce",		ARGS_1,				{NULL} },
  { U"defbreaktype",	ARGS_01,			{NULL} },
  { U"defc1",		ARGS_1,				{NULL} },
  { U"defcharset",       ARGS_01,			{NULL} },
  { U"defdynamictitle",	ARGS_1,				{NULL} },
  { U"defescape",	ARGS_1,				{NULL} },
  { U"defflow",		ARGS_12,			{NULL} },
  { U"defgr",		ARGS_1,				{NULL} },
  { U"defhstatus",	ARGS_01,			{NULL} },
  { U"defkanji",		ARGS_1,				{NULL} },
  { U"deflog",		ARGS_1,				{NULL} },
#if defined(ENABLE_UTMP)
  { U"deflogin",		ARGS_1,				{NULL} },
#endif
  { U"defmode",		ARGS_1,				{NULL} },
  { U"defmonitor",	ARGS_1,				{NULL} },
  { U"defmousetrack",	ARGS_1,				{NULL} },
  { U"defnonblock",	ARGS_1,				{NULL} },
  { U"defobuflimit",	ARGS_1,				{NULL} },
  { U"defscrollback",	ARGS_1,				{NULL} },
  { U"defshell",		ARGS_1,				{NULL} },
  { U"defsilence",	ARGS_1,				{NULL} },
  { U"defslowpaste",	ARGS_1,				{NULL} },
  { U"defutf8",		ARGS_1,				{NULL} },
  { U"defwrap",		ARGS_1,				{NULL} },
  { U"defwritelock",	ARGS_1,				{NULL} },
  { U"detach",		NEED_DISPLAY|ARGS_01,		{NULL} },
  { U"digraph",		NEED_LAYER|ARGS_012,		{NULL} },
  { U"dinfo",		NEED_DISPLAY|ARGS_0,		{NULL} },
  { U"displays",		NEED_LAYER|ARGS_0,		{NULL} },
  { U"dumptermcap",	NEED_FORE|ARGS_0,		{NULL} },
  { U"dynamictitle",	ARGS_1,				{NULL} },
  { U"echo",		CAN_QUERY|ARGS_12,		{NULL} },
  { U"escape",		ARGS_1,				{NULL} },
  { U"eval",		ARGS_1|ARGS_ORMORE,		{NULL} },
  { U"exec",		ARGS_0|ARGS_ORMORE,		{NULL} },
  { U"fit",		NEED_DISPLAY|ARGS_0,		{NULL} },
  { U"flow",		NEED_FORE|ARGS_01,		{NULL} },
  { U"focus",		NEED_DISPLAY|ARGS_01,		{NULL} },
  { U"focusminsize",	ARGS_02,			{NULL} },
  { U"gr",		NEED_FORE|ARGS_01,		{NULL} },
  { U"group",            NEED_FORE|ARGS_01,		{NULL} },
  { U"hardcopy",		NEED_FORE|ARGS_012,		{NULL} },
  { U"hardcopy_append",	ARGS_1,				{NULL} },
  { U"hardcopydir",	ARGS_01,			{NULL} },
  { U"hardstatus",	ARGS_012,			{NULL} },
  { U"height",		ARGS_0123,			{NULL} },
  { U"help",		NEED_LAYER|ARGS_02,		{NULL} },
  { U"history",		NEED_DISPLAY|NEED_FORE|ARGS_0,	{NULL} },
  { U"hstatus",		NEED_FORE|ARGS_1,		{NULL} },
  { U"idle",		ARGS_0|ARGS_ORMORE,		{NULL} },
  { U"ignorecase",	ARGS_01,			{NULL} },
  { U"info",		CAN_QUERY|NEED_LAYER|ARGS_0,	{NULL} },
  { U"kanji",		NEED_FORE|ARGS_12,		{NULL} },
  { U"kill",		NEED_FORE|ARGS_0,		{NULL} },
  { U"lastmsg",		CAN_QUERY|NEED_DISPLAY|ARGS_0,	{NULL} },
  { U"layout",           ARGS_1|ARGS_ORMORE,		{NULL} },
  { U"license",		NEED_LAYER|ARGS_0,		{NULL} },
  { U"lockscreen",	NEED_DISPLAY|ARGS_0,		{NULL} },
  { U"log",		NEED_FORE|ARGS_01,		{NULL} },
  { U"logfile",		ARGS_012,			{NULL} },
#if defined(ENABLE_UTMP)
  { U"login",		NEED_FORE|ARGS_01,		{NULL} },
#endif
  { U"logtstamp",	ARGS_012,			{NULL} },
  { U"mapdefault",	NEED_DISPLAY|ARGS_0,		{NULL} },
  { U"mapnotnext",	NEED_DISPLAY|ARGS_0,		{NULL} },
  { U"maptimeout",	ARGS_01,			{NULL} },
  { U"markkeys",		ARGS_1,				{NULL} },
  { U"maxwin",		ARGS_01,			{NULL} },
  { U"meta",		NEED_LAYER|ARGS_0,		{NULL} },
  { U"monitor",		NEED_FORE|ARGS_01,		{NULL} },
  { U"mousetrack",	NEED_DISPLAY | ARGS_01,		{NULL} },
  { U"msgminwait",	ARGS_1,				{NULL} },
  { U"msgwait",		ARGS_1,				{NULL} },
  { U"multiinput",	ARGS_01,			{NULL} },
  { U"multiuser",	ARGS_1,				{NULL} },
  { U"next",		ARGS_0,				{NULL} },
  { U"nonblock",		NEED_DISPLAY|ARGS_01,		{NULL} },
  { U"number",		CAN_QUERY|NEED_FORE|ARGS_01,	{NULL} },
  { U"obuflimit",	NEED_DISPLAY|ARGS_01,		{NULL} },
  { U"only",		NEED_DISPLAY|ARGS_0,		{NULL} },
  { U"other",		ARGS_0,				{NULL} },
  { U"partial",		NEED_FORE|ARGS_01,		{NULL} },
  { U"paste",		NEED_LAYER|ARGS_012,		{NULL} },
  { U"pastefont",	ARGS_01,			{NULL} },
  { U"pow_break",	NEED_FORE|ARGS_01,		{NULL} },
  { U"pow_detach",	NEED_DISPLAY|ARGS_0,		{NULL} },
  { U"pow_detach_msg",	ARGS_01,			{NULL} },
  { U"prev",		ARGS_0,				{NULL} },
  { U"printcmd",		ARGS_01,			{NULL} },
  { U"process",		NEED_DISPLAY|ARGS_01,		{NULL} },
  { U"quit",		ARGS_0,				{NULL} },
  { U"readbuf",		ARGS_0123,			{NULL} },
  { U"readreg",          ARGS_0|ARGS_ORMORE,		{NULL} },
  { U"redisplay",	NEED_DISPLAY|ARGS_0,		{NULL} },
  { U"register",		ARGS_24,			{NULL} },
  { U"remove",		NEED_DISPLAY|ARGS_0,		{NULL} },
  { U"removebuf",	ARGS_0,				{NULL} },
  { U"rendition",	ARGS_2,				{NULL} },
  { U"reset",		NEED_FORE|ARGS_0,		{NULL} },
  { U"resize",		NEED_DISPLAY|ARGS_0|ARGS_ORMORE,{NULL} },
  { U"screen",		ARGS_0|ARGS_ORMORE,		{NULL} },
  { U"scrollback",	NEED_FORE|ARGS_1,		{NULL} },
  { U"select",		CAN_QUERY|ARGS_01,		{NULL} },
  { U"sessionname",	ARGS_01,			{NULL} },
  { U"setenv",		ARGS_012,			{NULL} },
  { U"setsid",		ARGS_1,				{NULL} },
  { U"shell",		ARGS_1,				{NULL} },
  { U"shelltitle",	ARGS_1,				{NULL} },
  { U"silence",		NEED_FORE|ARGS_01,		{NULL} },
  { U"silencewait",	ARGS_1,				{NULL} },
  { U"sleep",		ARGS_1,				{NULL} },
  { U"slowpaste",	NEED_FORE|ARGS_01,		{NULL} },
  { U"sorendition",      ARGS_012,			{NULL} },
  { U"sort",		ARGS_0,				{NULL} },
  { U"source",		ARGS_1,				{NULL} },
  { U"split",		NEED_DISPLAY|ARGS_01,		{NULL} },
  { U"startup_message",	ARGS_1,				{NULL} },
  { U"status",		ARGS_12,			{NULL} },
  { U"stuff",		NEED_LAYER|ARGS_012,		{NULL} },
  { U"su",		NEED_DISPLAY|ARGS_012,		{NULL} },
  { U"suspend",		NEED_DISPLAY|ARGS_0,		{NULL} },
  { U"term",		ARGS_1,				{NULL} },
  { U"termcap",		ARGS_23,			{NULL} },
  { U"termcapinfo",	ARGS_23,			{NULL} },
  { U"terminfo",		ARGS_23,			{NULL} },
  { U"time",		CAN_QUERY|ARGS_01,		{NULL} },
  { U"title",		CAN_QUERY|NEED_FORE|ARGS_01,	{NULL} },
  { U"truecolor",	ARGS_1,				{NULL} },
  { U"umask",		ARGS_1|ARGS_ORMORE,		{NULL} },
  { U"unbindall",	ARGS_0,				{NULL} },
  { U"unsetenv",		ARGS_1,				{NULL} },
  { U"utf8",		NEED_FORE|ARGS_012,		{NULL} },
  { U"vbell",		ARGS_01,			{NULL} },
  { U"vbell_msg",	ARGS_01,			{NULL} },
  { U"vbellwait",	ARGS_1,				{NULL} },
  { U"verbose",		ARGS_01,			{NULL} },
  { U"version",		ARGS_0,				{NULL} },
  { U"wall",		NEED_DISPLAY|ARGS_1,		{NULL} },
  { U"width",		ARGS_0123,			{NULL} },
  { U"windowlist",	ARGS_012,			{NULL} },
  { U"windows",		CAN_QUERY|ARGS_01,		{NULL} },
  { U"wrap",		NEED_FORE|ARGS_01,		{NULL} },
  { U"writebuf",		ARGS_0123,			{NULL} },
  { U"writelock",	NEED_FORE|ARGS_01,		{NULL} },
  { U"xoff",		NEED_LAYER|ARGS_0,		{NULL} },
  { U"xon",		NEED_LAYER|ARGS_0,		{NULL} },
  { U"zmodem",		ARGS_012,			{NULL} },
  { U"zombie",		ARGS_012,			{NULL} },
  { U"zombie_timeout",	ARGS_1,				{NULL} }
};
