/* Copyright (c) 2008, 2009
 *      Juergen Weigert (jnweiger@immd4.informatik.uni-erlangen.de)
 *      Michael Schroeder (mlschroe@immd4.informatik.uni-erlangen.de)
 *      Micah Cowan (micah@cowan.name)
 *      Sadrul Habib Chowdhury (sadrul@users.sourceforge.net)
 * Copyright (c) 1993-2002, 2003, 2005, 2006, 2007
 *      Juergen Weigert (jnweiger@immd4.informatik.uni-erlangen.de)
 *      Michael Schroeder (mlschroe@immd4.informatik.uni-erlangen.de)
 * Copyright (c) 1987 Oliver Laumann
 *
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program (see the file COPYING); if not, see
 * http://www.gnu.org/licenses/, or contact Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA  02111-1301  USA
 *
 ****************************************************************
 */

#include "config.h"

#include "comm.h"

/* Must be in alpha order ! */

struct comm comms[RC_LAST + 1] =
{
  { "acladd",		ARGS_1234,			{NULL} },
  { "aclchg",		ARGS_23,			{NULL} },
  { "acldel",		ARGS_1,				{NULL} },
  { "aclgrp",		ARGS_12,			{NULL} },
  { "aclumask",		ARGS_1|ARGS_ORMORE,		{NULL} },
  { "activity",		ARGS_1,				{NULL} },
  { "addacl",		ARGS_1234,			{NULL} },
  { "allpartial",	ARGS_1,				{NULL} },
  { "altscreen",	ARGS_01,			{NULL} },
  { "at",		ARGS_2|ARGS_ORMORE,		{NULL} },
  { "autodetach",	ARGS_1,				{NULL} },
  { "autonuke",		ARGS_0,				{NULL} },
  { "backtick",		ARGS_1|ARGS_ORMORE,		{NULL} },
  { "bce",		ARGS_0,				{NULL} },
  { "bell",		ARGS_01,			{NULL} },
  { "bell_msg",		ARGS_01,			{NULL} },
  { "bind",		ARGS_1|ARGS_ORMORE,		{NULL} },
  { "bindkey",		ARGS_0|ARGS_ORMORE,		{NULL} },
  { "blanker",		ARGS_0,				{NULL} },
  { "blankerprg",	ARGS_0|ARGS_ORMORE,		{NULL} },
  { "break",		ARGS_01,			{NULL} },
  { "breaktype",	ARGS_01,			{NULL} },
  { "bufferfile",	ARGS_01,			{NULL} },
  { "bumpleft",		ARGS_0,				{NULL} },
  { "bumpright",	ARGS_0,				{NULL} },
  { "c1",		ARGS_01,			{NULL} },
  { "caption",		ARGS_123,			{NULL} },
  { "chacl",		ARGS_23,			{NULL} },
  { "charset",          ARGS_1,				{NULL} },
  { "chdir",		ARGS_01,			{NULL} },
  { "cjkwidth",		ARGS_01,			{NULL} },
  { "clear",		ARGS_0,				{NULL} },
  { "collapse",		ARGS_0,				{NULL} },
  { "colon",		ARGS_01,			{NULL} },
  { "command",		ARGS_02,			{NULL} },
  { "compacthist",	ARGS_01,			{NULL} },
  { "console",		ARGS_01,			{NULL} },
  { "copy",		ARGS_0,				{NULL} },
  { "crlf",		ARGS_01,			{NULL} },
  { "defautonuke",	ARGS_1,				{NULL} },
  { "defbce",		ARGS_1,				{NULL} },
  { "defbreaktype",	ARGS_01,			{NULL} },
  { "defc1",		ARGS_1,				{NULL} },
  { "defcharset",       ARGS_01,			{NULL} },
  { "defdynamictitle",	ARGS_1,				{NULL} },
  { "defencoding",	ARGS_1,				{NULL} },
  { "defescape",	ARGS_1,				{NULL} },
  { "defflow",		ARGS_12,			{NULL} },
  { "defgr",		ARGS_1,				{NULL} },
  { "defhstatus",	ARGS_01,			{NULL} },
  { "defkanji",		ARGS_1,				{NULL} },
  { "deflog",		ARGS_1,				{NULL} },
#if defined(ENABLE_UTMP)
  { "deflogin",		ARGS_1,				{NULL} },
#endif
  { "defmode",		ARGS_1,				{NULL} },
  { "defmonitor",	ARGS_1,				{NULL} },
  { "defmousetrack",	ARGS_1,				{NULL} },
  { "defnonblock",	ARGS_1,				{NULL} },
  { "defobuflimit",	ARGS_1,				{NULL} },
  { "defscrollback",	ARGS_1,				{NULL} },
  { "defshell",		ARGS_1,				{NULL} },
  { "defsilence",	ARGS_1,				{NULL} },
  { "defslowpaste",	ARGS_1,				{NULL} },
  { "defutf8",		ARGS_1,				{NULL} },
  { "defwrap",		ARGS_1,				{NULL} },
  { "defwritelock",	ARGS_1,				{NULL} },
  { "detach",		ARGS_01,			{NULL} },
  { "digraph",		ARGS_012,			{NULL} },
  { "dinfo",		ARGS_0,				{NULL} },
  { "displays",		ARGS_0,				{NULL} },
  { "dumptermcap",	ARGS_0,				{NULL} },
  { "dynamictitle",	ARGS_1,				{NULL} },
  { "echo",		ARGS_12,			{NULL} },
  { "encoding",		ARGS_12,			{NULL} },
  { "escape",		ARGS_1,				{NULL} },
  { "eval",		ARGS_1|ARGS_ORMORE,		{NULL} },
  { "exec",		ARGS_0|ARGS_ORMORE,		{NULL} },
  { "fit",		ARGS_0,				{NULL} },
  { "flow",		ARGS_01,			{NULL} },
  { "focus",		ARGS_01,			{NULL} },
  { "focusminsize",	ARGS_02,			{NULL} },
  { "gr",		ARGS_01,			{NULL} },
  { "group",            ARGS_01,			{NULL} },
  { "hardcopy",		ARGS_012,			{NULL} },
  { "hardcopy_append",	ARGS_1,				{NULL} },
  { "hardcopydir",	ARGS_01,			{NULL} },
  { "hardstatus",	ARGS_012,			{NULL} },
  { "height",		ARGS_0123,			{NULL} },
  { "help",		ARGS_02,			{NULL} },
  { "history",		ARGS_0,				{NULL} },
  { "hstatus",		ARGS_1,				{NULL} },
  { "idle",		ARGS_0|ARGS_ORMORE,		{NULL} },
  { "ignorecase",	ARGS_01,			{NULL} },
  { "info",		ARGS_0,				{NULL} },
  { "kanji",		ARGS_12,			{NULL} },
  { "kill",		ARGS_01,			{NULL} },
  { "lastmsg",		ARGS_0,				{NULL} },
  { "layout",           ARGS_1|ARGS_ORMORE,		{NULL} },
  { "license",		ARGS_0,				{NULL} },
  { "lockscreen",	ARGS_0,				{NULL} },
  { "log",		ARGS_01,			{NULL} },
  { "logfile",		ARGS_012,			{NULL} },
#if defined(ENABLE_UTMP)
  { "login",		ARGS_01,			{NULL} },
#endif
  { "logtstamp",	ARGS_012,			{NULL} },
  { "mapdefault",	ARGS_0,				{NULL} },
  { "mapnotnext",	ARGS_0,				{NULL} },
  { "maptimeout",	ARGS_01,			{NULL} },
  { "markkeys",		ARGS_1,				{NULL} },
  { "meta",		ARGS_0,				{NULL} },
  { "monitor",		ARGS_01,			{NULL} },
  { "mousetrack",	ARGS_01,			{NULL} },
  { "msgminwait",	ARGS_1,				{NULL} },
  { "msgwait",		ARGS_1,				{NULL} },
  { "multiinput",	ARGS_01,			{NULL} },
  { "multiuser",	ARGS_1,				{NULL} },
  { "next",		ARGS_0,				{NULL} },
  { "nonblock",		ARGS_01,			{NULL} },
  { "number",		ARGS_01,			{NULL} },
  { "obuflimit",	ARGS_01,			{NULL} },
  { "only",		ARGS_0,				{NULL} },
  { "other",		ARGS_0,				{NULL} },
  { "parent",		ARGS_0,				{NULL} },
  { "partial",		ARGS_01,			{NULL} },
  { "paste",		ARGS_012,			{NULL} },
  { "pastefont",	ARGS_01,			{NULL} },
  { "pow_break",	ARGS_01,			{NULL} },
  { "pow_detach",	ARGS_01,			{NULL} },
  { "pow_detach_msg",	ARGS_01,			{NULL} },
  { "prev",		ARGS_0,				{NULL} },
  { "printcmd",		ARGS_01,			{NULL} },
  { "process",		ARGS_01,			{NULL} },
  { "quit",		ARGS_01,			{NULL} },
  { "readbuf",		ARGS_0123,			{NULL} },
  { "readreg",          ARGS_0|ARGS_ORMORE,		{NULL} },
  { "redisplay",	ARGS_0,				{NULL} },
  { "register",		ARGS_24,			{NULL} },
  { "remove",		ARGS_0,				{NULL} },
  { "removebuf",	ARGS_0,				{NULL} },
  { "rendition",	ARGS_2,				{NULL} },
  { "reset",		ARGS_0,				{NULL} },
  { "resize",		ARGS_0|ARGS_ORMORE,		{NULL} },
  { "screen",		ARGS_0|ARGS_ORMORE,		{NULL} },
  { "scrollback",	ARGS_1,				{NULL} },
  { "select",		ARGS_01,			{NULL} },
  { "sessionname",	ARGS_01,			{NULL} },
  { "setenv",		ARGS_012,			{NULL} },
  { "setsid",		ARGS_1,				{NULL} },
  { "shell",		ARGS_1,				{NULL} },
  { "shelltitle",	ARGS_1,				{NULL} },
  { "silence",		ARGS_01,			{NULL} },
  { "silencewait",	ARGS_1,				{NULL} },
  { "sleep",		ARGS_1,				{NULL} },
  { "slowpaste",	ARGS_01,			{NULL} },
  { "sorendition",      ARGS_012,			{NULL} },
  { "sort",		ARGS_0,				{NULL} },
  { "source",		ARGS_1,				{NULL} },
  { "split",		ARGS_01,			{NULL} },
  { "startup_message",	ARGS_1,				{NULL} },
  { "status",		ARGS_12,			{NULL} },
  { "stuff",		ARGS_012,			{NULL} },
  { "su",		ARGS_012,			{NULL} },
  { "suspend",		ARGS_0,				{NULL} },
  { "term",		ARGS_1,				{NULL} },
  { "termcap",		ARGS_23,			{NULL} },
  { "termcapinfo",	ARGS_23,			{NULL} },
  { "terminfo",		ARGS_23,			{NULL} },
  { "title",		ARGS_01,			{NULL} },
  { "truecolor",	ARGS_1,				{NULL} },
  { "umask",		ARGS_1|ARGS_ORMORE,		{NULL} },
  { "unbindall",	ARGS_0,				{NULL} },
  { "unsetenv",		ARGS_1,				{NULL} },
  { "utf8",		ARGS_012,			{NULL} },
  { "vbell",		ARGS_01,			{NULL} },
  { "vbell_msg",	ARGS_01,			{NULL} },
  { "vbellwait",	ARGS_1,				{NULL} },
  { "verbose",		ARGS_01,			{NULL} },
  { "version",		ARGS_0,				{NULL} },
  { "wall",		ARGS_1,				{NULL} },
  { "width",		ARGS_0123,			{NULL} },
  { "windowlist",	ARGS_012,			{NULL} },
  { "windows",		ARGS_01,			{NULL} },
  { "wrap",		ARGS_01,			{NULL} },
  { "writebuf",		ARGS_0123,			{NULL} },
  { "writelock",	ARGS_01,			{NULL} },
  { "xoff",		ARGS_0,				{NULL} },
  { "xon",		ARGS_0,				{NULL} },
  { "zmodem",		ARGS_012,			{NULL} },
  { "zombie",		ARGS_012,			{NULL} },
  { "zombie_timeout",	ARGS_1,				{NULL} }
};
